import Link from "next/link";

/**
 * Wraps every route under /lab. This persists across navigation between
 * experiments — it does not re-mount, so state up here survives.
 * (Use `template.tsx` instead of `layout.tsx` if you ever want the opposite.)
 *
 * `LayoutProps` is a global type generated by `next dev` / `next build`.
 * No import needed.
 */
export default function LabLayout({ children }: LayoutProps<"/lab">) {
  return (
    <div className="min-h-dvh bg-white">
      <nav className="fixed left-0 top-0 z-50 p-6">
        <Link
          href="/"
          className="font-mono text-xs text-zinc-400 transition-colors hover:text-zinc-900"
        >
          ← index
        </Link>
      </nav>
      {children}
    </div>
  );
}
